# Non-interactive NoLlama install for Hermes: Qwen3 14B INT4 on Intel GPU (Arc).
# Usage: pwsh -File install_hermes_gpu.ps1 [-NollamaHome C:\Users\Rudol\NoLlama]

param(
    [string]$NollamaHome = $(if ($env:NOLLAMA_HOME) { $env:NOLLAMA_HOME } else { "C:\Users\Rudol\NoLlama" })
)

$ErrorActionPreference = "Stop"
$HfModel = "OpenVINO/Qwen3-14B-int4-ov"
$CacheName = ($HfModel -split '/')[-1]
$ModelsRoot = Join-Path $HOME "models"
$CachePath = Join-Path $ModelsRoot $CacheName
$ModelDir = Join-Path $NollamaHome "model"

Write-Host "=== Hermes NoLlama GPU install ===" -ForegroundColor Cyan
Write-Host "NOLLAMA_HOME: $NollamaHome"

if (-not (Test-Path (Join-Path $NollamaHome "nollama.py"))) {
    Write-Host "ERROR: nollama.py not found. Clone first:" -ForegroundColor Red
    Write-Host "  git clone https://github.com/aweussom/NoLlama `"$NollamaHome`""
    exit 1
}

Push-Location $NollamaHome

# 1) venv + deps via upstream install.ps1 -SkipModel
Write-Host "[1/4] venv + dependencies..."
& (Join-Path $NollamaHome "install.ps1") -SkipModel
if (-not $?) { Pop-Location; exit 1 }

# 2) Download model (~8 GB) if missing
function Test-ModelCacheValid([string]$Path) {
    if (-not (Test-Path $Path)) { return $false }
    foreach ($bin in @("openvino_language_model.bin", "openvino_model.bin")) {
        $file = Join-Path $Path $bin
        if ((Test-Path $file) -and ((Get-Item $file).Length -gt 100MB)) { return $true }
    }
    return $false
}

New-Item -ItemType Directory -Path $ModelsRoot -Force | Out-Null
if (Test-ModelCacheValid -Path $CachePath) {
    Write-Host "[2/4] Model cache hit: $CachePath" -ForegroundColor Green
} else {
    if (Test-Path $CachePath) { Remove-Item -Recurse -Force $CachePath }
    Write-Host "[2/4] Downloading $HfModel (~8 GB). This may take a while..."
    $env:PYTHONIOENCODING = "utf-8"
    & (Join-Path $NollamaHome "venv\Scripts\Activate.ps1")
    hf download $HfModel --local-dir $CachePath
    if (-not $?) { Pop-Location; exit 1 }
}

# 3) Junction model/ -> cache
if (Test-Path $ModelDir) {
    $item = Get-Item $ModelDir -Force
    if ($item.LinkType) { cmd /c rmdir "`"$ModelDir`"" | Out-Null }
    else { Remove-Item -Recurse -Force $ModelDir }
}
cmd /c mklink /J "`"$ModelDir`"" "`"$CachePath`"" | Out-Null
Write-Host "[3/4] Linked model -> $CachePath" -ForegroundColor Green

# 4) start.ps1 with GPU device
$StartScript = Join-Path $NollamaHome "start.ps1"
$Template = Join-Path $NollamaHome "start-template.ps1"
$Content = "# Auto-generated by Hermes install_hermes_gpu.ps1`n"
$Content += "& '$Template' -ServerArgs '--device GPU'"
Set-Content -Path $StartScript -Value $Content -Encoding UTF8
Write-Host "[4/4] Generated start.ps1 (--device GPU)" -ForegroundColor Green

Pop-Location
Write-Host ""
Write-Host "=== Install complete ===" -ForegroundColor Green
Write-Host "Set persistent env (new CMD after setx):"
Write-Host "  setx NOLLAMA_HOME `"$NollamaHome`""
Write-Host "  setx HERMES_CHAT_MODEL `"qwen3-14b-int4`""
Write-Host "Next: scripts\run_intel_gpu\01_start_nollama.bat"
