"""Ensure Hermes generated/ output folders are DAEDALUS campaign-ready.

Every folder under generated/ that HERMES produces must carry:
  * tests/          — verification gauntlet (R22)
  * config.py       — smoke knobs for measurable mutations
  * daedalus_manifest.json — machine-readable readiness stamp

Called from output_paths.bind_generated_output after the output directory is created.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

_DEFAULT_CONFIG = '''"""Smoke configuration for DAEDALUS RSI campaigns (auto-generated by HERMES)."""

from __future__ import annotations

import os

SMOKE = os.getenv("HERMES_RSI_SMOKE", "1") == "1"
LIMIT_BARS = 500 if SMOKE else 50_000
'''


def ensure_daedalus_campaign_ready(out_dir: Path, *, slug: str) -> dict[str, Any]:
    """Materialize missing DAEDALUS prerequisites under a generated folder."""
    out_dir = Path(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    created: list[str] = []

    tests_dir = out_dir / "tests"
    if not tests_dir.is_dir():
        tests_dir.mkdir(parents=True, exist_ok=True)
        smoke = tests_dir / "test_smoke_import.py"
        smoke.write_text(
            '"""Smoke import test — ensures package loads under DAEDALUS R22."""\n\n'
            "def test_smoke_import():\n"
            '    import config  # noqa: F401\n'
            "    assert True\n",
            encoding="utf-8",
        )
        created.append("tests/test_smoke_import.py")

    cfg = out_dir / "config.py"
    if not cfg.is_file():
        cfg.write_text(_DEFAULT_CONFIG, encoding="utf-8")
        created.append("config.py")

    manifest_path = out_dir / "daedalus_manifest.json"
    manifest = {
        "slug": slug,
        "campaign_ready": True,
        "has_tests": (out_dir / "tests").is_dir(),
        "has_config": cfg.is_file(),
        "hermes_export": True,
    }
    manifest_path.write_text(json.dumps(manifest, indent=2), encoding="utf-8")
    if not manifest_path.exists():
        created.append("daedalus_manifest.json")

    return {"ok": True, "slug": slug, "created": created, "manifest": manifest}
